### ISSUE TITLE
Wheneverを使用して定期的にタスクの実行ができない

### ISSUE THREAD

**Issue by sugimorikota** [sugimorikota/pokemon_janken#37]
## 実装したい機能
毎日AM9:00 にUserPokemonMatchのmatch_limitカラムの値を10にして、
"残り対戦回数がリセットされました。"というメッセージの通知をユーザーに届くようにする。
※whenever/cronを使用する

## 解決できない問題
作成したrakeタスクはターミナル上で実行すると上手く動作するのですが、
wheneverを使用して定期実行ができません。
エラー内容を見て色々調べてみても詳しい原因まではわからず、解決方法がわかりませんでした。

## 事象
* 単体で実行（成功します）
update_match_limit.rake
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/848276f7-1440-421f-b9a3-a46e6270258b)

self.update_match_limitメソッド
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/6e939166-7a32-4a3e-8aea-700cf3424ba0)

schedule.rb（確認のため1分ごとに実行してます）
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/61beadc3-c9d9-44dd-bf23-51c33379098b)

rake update_match_limit:reset_match_limit実行（成功してます）
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/85c737d5-6ad7-4a93-b3d1-fa691d4f8523)
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/51f35ed3-1ce0-41e4-91b8-17650447c62e)

* 定期的に実行時（失敗してます）
cron.log（このエラーが繰り返されます）
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.4.14) required by your /Users/sugimorikouta/workspace/pokemon_janken/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.4.14`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'

bundlerのバージョン(2.4.14)
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/63a7d6ef-dda1-4103-9c87-ff18e7602ca6)

Gemfile.lock
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/f12bb993-f359-45d0-8409-d066547fc920)

cronタブ反映後、wheneverコマンド実行（反映されてないエラーが出てます）
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/54912300-077f-440c-8d44-708096cde412)

## 原因
bundlerのバージョンが合っていない
→ターミナルやGemfile.lockで確認すると2.4.14であっているので、他に原因があるのかなと思っています。

wheneverコマンド実行で反映されてないエラーが出る
→ bundle exec whenever --update-crontab　実行時にはエラーが出てないので詳しい原因がわかりませんでした。

カリキュラムの応用課題4, 10の質問などを見てもわからず、よく分からないまま色々変更するのも危ない気がしたので質問させていただきます。
お手数をおかけしますが、ご確認をお願いいたします。

**Comment by Tsuchiya2** [comment]
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in find_spec_for_exe': Could not find 'bundler' (2.4.14) required by your 

↑のログからRubyの2.6系を使用して実行しようとしているのではないかと推測できます。（おそらく元々PCに入っているRubyのバージョンが2.6.10とかの可能性あり）

schedule.rbに書かれているパスを通すコマンドの部分が、ご自身のPCに対して適切な記載になっていないのかもしれません。その辺りを調べてみて、仮説立て・検証のサイクルを回してみてください。（ローカルのパス部分の設定と記載にズレが無いかなども合わせて確認してみましょう）

**Comment by sugimorikota** [comment]
Ruby2.6系が使用されてしまうので
・rbenv globalでバージョンを3.2.2にする。
・.zshrcを確認してパスを修正する。
こちらの2つを試しましたが、変わらず同じエラーログが出てしまいます。
（Ruby2.6系が使用されてしまう原因がわからないままです）

> （おそらく元々PCに入っているRubyのバージョンが2.6.10とかの可能性あり）

こちらについて、変更する方法をrbenv globalで変更すると考えたのですがこちらの考え方が間違っているのでしょうか？
ご確認をお願いいたします。


** キャプチャ
schedule.rbのパスを通すコマンドを修正
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/618a6e1f-24db-4b7d-8b50-5d82624a3914)

.zshrcを見てパスが正しいか確認
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/f3d61762-e81f-4c39-aeaa-ffaaa1251153)

bundle envコマンドでRubyのバージョン確認
![image](https://github.com/sugimorikota/pokemon_janken/assets/129940394/391959a1-5136-4506-9fb4-a0cd8fbf105f)

cron.log
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.5.6) required by your /Users/sugimorikouta/workspace/pokemon_janken/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.5.6`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'

**Comment by Tsuchiya2** [comment]
rbenv globalはローカルのPCで使用するRubyのバージョン指定ですが、rbenv localの方が優先されるので、その辺りの確認も必要かもしれません。

また、もしDockerでの開発を行っている場合、動いているのは手元のPCではなく、コンテナのLinux上のため、設定がそもそも異なるので、そちらも確認してみると良いかもしれません。

cron.logが変わらず...2.6.0..が出ているところを見ると、設定が上手くいっていない状況は変わっていないかと思われます。 もしくはデプロイ先をherokuにして[Heroku Scheduler](https://devcenter.heroku.com/ja/articles/scheduler)を使うなど、他の方法も検討してみるのもありです。

**Comment by sugimorikota** [comment]
Herokuでデプロイしたので、Heroku Schedulerで解決しました。
ありがとうございました。
